Warning: Permanently added '34.216.164.248' (ED25519) to the list of known hosts.
"""
AllToAllV: Optimized implementation for AWS Trainium.

Generated by the LLM-guided algorithm evolution agent.
"""

import torch
import torch_xla.core.xla_model as xm
import torch_xla.runtime as xr

_WORLD = 224
_NUM_DEVICES = 112
_NUM_NODES = 7
_CORES_PER_DEVICE = 2

_rank = None
_world_size = None


def init_alltoallv():
    """Initialize rank/world info. Call once after dist.init_process_group."""
    global _rank, _world_size
    _rank = xr.global_ordinal()
    _world_size = xr.world_size()


# Agent-evolved algorithm
def evolved_alltoallv(input_tensor, send_counts, recv_counts, max_chunk,
                      rank, world_size, num_devices, cores_per_device,
                      xm, torch, num_nodes=1):
    """All-gather then per-source slice + cat."""
    pack_size = world_size * max_chunk
    packed = torch.zeros(pack_size, device=input_tensor.device, dtype=input_tensor.dtype)
    send_off = 0
    for i in range(world_size):
        sc = send_counts[i]
        if sc > 0:
            packed[i * max_chunk:i * max_chunk + sc] = input_tensor[send_off:send_off + sc]
        send_off += sc
    gathered = xm.all_gather(packed.unsqueeze(0), dim=0).view(-1)
    chunks = []
    for src in range(world_size):
        count = recv_counts[src]
        base = src * pack_size + rank * max_chunk
        chunks.append(gathered[base:base + count])
    return torch.cat(chunks)



# ================================================================
# Public API
# ================================================================

def compute_recv_counts(send_counts):
    """Exchange send_counts to derive recv_counts via all_gather."""
    device = xm.xla_device()
    t = torch.tensor(send_counts, device=device, dtype=torch.int32)
    gathered = xm.all_gather(t)
    gathered = gathered.view(_world_size, _world_size)
    return gathered[:, _rank].tolist()


def all_to_allv(x, send_counts, recv_counts=None, max_chunk=None):
    """Perform AllToAllV using the agent-evolved algorithm."""
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")
    if recv_counts is None:
        recv_counts = compute_recv_counts(send_counts)
    if max_chunk is None:
        max_chunk = max(max(send_counts), max(recv_counts), 1)
    return evolved_alltoallv(
        x, send_counts, recv_counts, max_chunk,
        _rank, _world_size, _NUM_DEVICES, _CORES_PER_DEVICE,
        xm, torch, num_nodes=_NUM_NODES)


def alltoallv(x, world_size, max_chunk):
    """Pre-packed uniform AllToAllV. Vectorised: allgather then extract
    rank-owned column via a single narrow (no Python for-loop over ws)."""
    if _rank is None:
        raise RuntimeError("Call init_alltoallv() first")
    rank = _rank
    ws = world_size
    mc = max_chunk
    # allgather: (1, ws*mc) -> (ws, ws*mc) then reshape to (ws, ws, mc)
    gathered = xm.all_gather(x.unsqueeze(0), dim=0).view(ws, ws, mc)
    # this rank owns column "rank" from every source
    my_col = gathered[:, rank, :].contiguous()  # (ws, mc)
    return my_col.view(-1)


